/*
Copyright 2025 SK Telecom.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/petasus-ai/accelerator-operator/api/petasus/v1beta1"
	petasusv1beta1 "github.com/petasus-ai/accelerator-operator/api/versioned/typed/petasus/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAcceleratorConfigs implements AcceleratorConfigInterface
type fakeAcceleratorConfigs struct {
	*gentype.FakeClientWithList[*v1beta1.AcceleratorConfig, *v1beta1.AcceleratorConfigList]
	Fake *FakePetasusV1beta1
}

func newFakeAcceleratorConfigs(fake *FakePetasusV1beta1) petasusv1beta1.AcceleratorConfigInterface {
	return &fakeAcceleratorConfigs{
		gentype.NewFakeClientWithList[*v1beta1.AcceleratorConfig, *v1beta1.AcceleratorConfigList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("acceleratorconfigs"),
			v1beta1.SchemeGroupVersion.WithKind("AcceleratorConfig"),
			func() *v1beta1.AcceleratorConfig { return &v1beta1.AcceleratorConfig{} },
			func() *v1beta1.AcceleratorConfigList { return &v1beta1.AcceleratorConfigList{} },
			func(dst, src *v1beta1.AcceleratorConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.AcceleratorConfigList) []*v1beta1.AcceleratorConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.AcceleratorConfigList, items []*v1beta1.AcceleratorConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
