apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rebellions-vfio-manager
  namespace: rebellions
  labels:
    app: rebellions-vfio-manager
spec:
  selector:
    matchLabels:
      name: rebellions-vfio-manager
  template:
    metadata:
      labels:
        name: rebellions-vfio-manager
    spec:
      tolerations:
        - key: rebellions.ai/npu
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        rebellions.ai/npu.deploy.vfio-manager: "true"
      priorityClassName: system-node-critical
      serviceAccountName: rebellions-vfio-manager
      containers:
        - name: rebellions-vfio-manager
          image: "docker.io/redhat/ubi8:8.10"
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - /bin/vfio-manage.sh bind --all && sleep inf
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
          - name: rebellions-vfio-manager
            readOnly: true
            mountPath: /bin/vfio-manage.sh
            subPath: vfio-manage.sh
          - name: host-sys
            mountPath: /sys
          - name: host-root
            mountPath: /host
          securityContext:
            privileged: true
            seLinuxOptions:
              level: "s0"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/vfio-manage.sh unbind --all"]
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rebellions-vfio-manager
          configMap:
            name: rebellions-vfio-manager
            defaultMode: 448
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: host-root
          hostPath:
            path: "/"
