apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rebellions-vfio-manager
  namespace: rebellions
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
