apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rebellions-vfio-manager
  namespace: rebellions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rebellions-vfio-manager
subjects:
- kind: ServiceAccount
  name: rebellions-vfio-manager
  namespace: rebellions
